package Theming;
use strict;
use warnings;

my %themes = (
    'nord' => {
        background  => '#2e3440',
        foreground  => '#d8dee9',
        color0      => '#3b4252',
        color1      => '#bf616a',
        color2      => '#a3be8c',
        color3      => '#ebcb8b',
        color4      => '#81a1c1',
        color5      => '#b48ead',
        color6      => '#88c0d0',
        color7      => '#e5e9f0',
    },
    'gruvbox' => {
        background  => '#282828',
        foreground  => '#ebdbb2',
        color0      => '#282828',
        color1      => '#cc241d',
        color2      => '#98971a',
        color3      => '#d79921',
        color4      => '#458588',
        color5      => '#b16286',
        color6      => '#689d6a',
        color7      => '#a89984',
    },
    'dracula' => {
        background  => '#282a36',
        foreground  => '#f8f8f2',
        color0      => '#21222c',
        color1      => '#ff5555',
        color2      => '#50fa7b',
        color3      => '#f1fa8c',
        color4      => '#bd93f9',
        color5      => '#ff79c6',
        color6      => '#8be9fd',
        color7      => '#f8f8f2',
    },
);

sub setup {
    my ($theme, $dry_run) = @_;
    print "Applying theme: $theme\n";

    if ($dry_run) {
        print "[Dry-run] Would apply $theme theme to .Xresources.\n";
        return;
    }

    my $colors = $themes{$theme};
    unless ($colors) {
        print "Unknown theme: $theme. Skipping theming.\n";
        return;
    }

    # Append theme colors to .Xresources
    my $xresources_path = "$ENV{HOME}/.Xresources";
    open my $fh, '>>', $xresources_path
        or die "Could not open $xresources_path: $!";

    print $fh "\n! $theme theme - generated by bonsai\n";
    print $fh "*background: $colors->{background}\n";
    print $fh "*foreground: $colors->{foreground}\n";
    print $fh "*color0: $colors->{color0}\n";
    print $fh "*color1: $colors->{color1}\n";
    print $fh "*color2: $colors->{color2}\n";
    print $fh "*color3: $colors->{color3}\n";
    print $fh "*color4: $colors->{color4}\n";
    print $fh "*color5: $colors->{color5}\n";
    print $fh "*color6: $colors->{color6}\n";
    print $fh "*color7: $colors->{color7}\n";
    # Bright variants (same as normal for simplicity)
    print $fh "*color8: $colors->{color0}\n";
    print $fh "*color9: $colors->{color1}\n";
    print $fh "*color10: $colors->{color2}\n";
    print $fh "*color11: $colors->{color3}\n";
    print $fh "*color12: $colors->{color4}\n";
    print $fh "*color13: $colors->{color5}\n";
    print $fh "*color14: $colors->{color6}\n";
    print $fh "*color15: $colors->{color7}\n";

    close $fh;
    print "Theme $theme applied to .Xresources\n";
    print "Run 'xrdb -merge ~/.Xresources' to apply changes.\n";
}

1;
