package WindowManager;
use strict;
use warnings;

my %wm_packages = (
    'cwm'      => undef,  # included in base
    'spectrwm' => 'spectrwm',
    'i3'       => 'i3',
    'dwm'      => 'dwm',
    'bspwm'    => 'bspwm',
    'openbox'  => 'openbox',
);

sub setup {
    my ($wm, $dry_run) = @_;
    print "Setting up window manager: $wm\n";

    if ($dry_run) {
        print "[Dry-run] Would configure $wm as window manager.\n";
        return;
    }

    # Install window manager if not in base
    if (exists $wm_packages{$wm} && defined $wm_packages{$wm}) {
        my $pkg = $wm_packages{$wm};
        print "Installing $pkg...\n";
        system("pkg_add $pkg") == 0
            or warn "Warning: Failed to install $pkg\n";
    } elsif (!exists $wm_packages{$wm}) {
        print "Unknown window manager: $wm. Attempting to install...\n";
        system("pkg_add $wm") == 0
            or warn "Warning: Failed to install $wm\n";
    } else {
        print "$wm is included in OpenBSD base, no installation needed.\n";
    }

    # Create .xinitrc
    my $xinitrc_path = "$ENV{HOME}/.xinitrc";
    open my $fh, '>', $xinitrc_path
        or die "Could not open $xinitrc_path: $!";
    print $fh "#!/bin/sh\n";
    print $fh "# Generated by bonsai\n\n";
    print $fh "xsetroot -solid black\n";
    print $fh "exec $wm\n";
    close $fh;
    chmod 0755, $xinitrc_path;

    print "Window manager $wm configured. Start X with 'startx' or use xenodm.\n";
}

1;
