package Xorg;
use strict;
use warnings;

sub setup {
    my ($resolution, $brightness, $dry_run) = @_;
    print "Configuring Xorg: resolution=$resolution, brightness=$brightness%\n";

    if ($dry_run) {
        print "[Dry-run] Would configure Xorg with resolution $resolution and brightness $brightness%.\n";
        return;
    }

    # Create .Xresources with sensible defaults
    my $xresources_path = "$ENV{HOME}/.Xresources";
    open my $fh, '>', $xresources_path
        or die "Could not open $xresources_path: $!";

    print $fh "! Generated by bonsai\n\n";
    print $fh "! Font settings\n";
    print $fh "Xft.dpi: 96\n";
    print $fh "Xft.antialias: true\n";
    print $fh "Xft.hinting: true\n";
    print $fh "Xft.hintstyle: hintslight\n";
    print $fh "Xft.rgba: rgb\n\n";
    print $fh "! xterm settings\n";
    print $fh "xterm*faceName: monospace\n";
    print $fh "xterm*faceSize: 11\n";
    print $fh "xterm*termName: xterm-256color\n";
    print $fh "xterm*saveLines: 10000\n";
    print $fh "xterm*scrollBar: false\n";

    close $fh;
    print "Created $xresources_path\n";

    # Set brightness if xbacklight is available
    if ($brightness && -x '/usr/X11R6/bin/xbacklight') {
        print "Setting brightness to $brightness%...\n";
        system("xbacklight -set $brightness 2>/dev/null");
    }

    # Create .xsession for xenodm users
    my $xsession_path = "$ENV{HOME}/.xsession";
    unless (-e $xsession_path) {
        open my $xfh, '>', $xsession_path
            or die "Could not open $xsession_path: $!";
        print $xfh "#!/bin/sh\n";
        print $xfh "# Generated by bonsai\n\n";
        print $xfh "xrdb -merge ~/.Xresources\n";
        print $xfh ". ~/.xinitrc\n";
        close $xfh;
        chmod 0755, $xsession_path;
        print "Created $xsession_path\n";
    }

    print "Xorg configuration complete.\n";
}

1;
