#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long;
use FindBin;
use File::Path qw(make_path);
use lib "$FindBin::Bin/modules";

use Browser;
use DefaultApps;
use Shell;
use SSHAgent;
use Theming;
use WindowManager;
use Xorg;

our $VERSION = '0.2.0';

# Command line options
my $dry_run = 0;
my $help = 0;
my $man = 0;
my $version = 0;
my $interactive = 0;
my $config_only = 0;

GetOptions(
    "dry-run"     => \$dry_run,
    "help"        => \$help,
    "man"         => \$man,
    "version"     => \$version,
    "interactive" => \$interactive,
    "config"      => \$config_only,
) or die("Error in command line arguments\n");

# Display version
if ($version) {
    print "bonsai version $VERSION\n";
    exit 0;
}

# Display help
if ($help) {
    print "bonsai - A minimalist OpenBSD setup tool\n\n";
    print "Usage: bonsai.pl [options]\n\n";
    print "Options:\n";
    print "  --dry-run      Show what would be done without making changes\n";
    print "  --interactive  Prompt for each setting interactively\n";
    print "  --config       Generate config file only, don't run setup\n";
    print "  --help         Display this help message\n";
    print "  --man          Display the manual page\n";
    print "  --version      Display version information\n";
    exit 0;
}

# Display man page
if ($man) {
    exec("man $FindBin::Bin/bonsai.man");
}

# Config file path
my $config_dir = "$ENV{HOME}/.config/bonsai";
my $config_file = "$config_dir/config.conf";

# Default settings
my %settings = (
    window_manager   => 'cwm',
    browser          => 'firefox',
    theme            => 'nord',
    shell            => 'ksh',
    xorg_resolution  => '1920x1080',
    xorg_brightness  => '80',
);

# Load config file if it exists
sub load_config {
    return unless -f $config_file;

    open my $fh, '<', $config_file
        or die "Could not open $config_file: $!";

    while (<$fh>) {
        chomp;
        next if /^\s*#/ || /^\s*$/;  # Skip comments and empty lines
        if (/^(\w+)\s*=\s*(.+)$/) {
            my ($key, $value) = ($1, $2);
            $value =~ s/^\s+|\s+$//g;  # Trim whitespace
            $settings{$key} = $value if exists $settings{$key};
        }
    }
    close $fh;
    print "Loaded configuration from $config_file\n";
}

# Save config file
sub save_config {
    make_path($config_dir) unless -d $config_dir;

    open my $fh, '>', $config_file
        or die "Could not open $config_file: $!";

    print $fh "# bonsai configuration file\n";
    print $fh "# Generated by bonsai v$VERSION\n\n";

    for my $key (sort keys %settings) {
        print $fh "$key = $settings{$key}\n";
    }
    close $fh;
    print "Configuration saved to $config_file\n";
}

# Interactive prompts
sub prompt {
    my ($message, $default, @options) = @_;

    if (@options) {
        print "$message\n";
        for my $i (0..$#options) {
            my $marker = ($options[$i] eq $default) ? '*' : ' ';
            printf "  %s %d) %s\n", $marker, $i + 1, $options[$i];
        }
        print "Choice [$default]: ";
    } else {
        print "$message [$default]: ";
    }

    my $input = <STDIN>;
    chomp $input;

    if (@options && $input =~ /^\d+$/) {
        my $idx = $input - 1;
        return $options[$idx] if $idx >= 0 && $idx <= $#options;
    }

    return $input || $default;
}

sub run_interactive {
    print "\n=== bonsai interactive setup ===\n\n";

    $settings{window_manager} = prompt(
        "Select window manager:",
        $settings{window_manager},
        qw(cwm spectrwm i3 dwm bspwm openbox)
    );

    $settings{shell} = prompt(
        "Select shell:",
        $settings{shell},
        qw(ksh fish zsh bash)
    );

    $settings{browser} = prompt(
        "Select browser:",
        $settings{browser},
        qw(firefox librewolf chromium lynx)
    );

    $settings{theme} = prompt(
        "Select color theme:",
        $settings{theme},
        qw(nord gruvbox dracula)
    );

    $settings{xorg_resolution} = prompt(
        "Xorg resolution",
        $settings{xorg_resolution}
    );

    $settings{xorg_brightness} = prompt(
        "Screen brightness (0-100)",
        $settings{xorg_brightness}
    );

    print "\n";
}

# Main execution
load_config();

if ($interactive) {
    run_interactive();
    save_config();
}

if ($config_only) {
    save_config() unless $interactive;  # Already saved if interactive
    print "Config file ready. Run 'bonsai.pl' to apply settings.\n";
    exit 0;
}

# Dry-run message
if ($dry_run) {
    print "\n=== Running in dry-run mode. No changes will be made. ===\n\n";
}

print "=== bonsai setup starting ===\n\n";

# Run setup modules
WindowManager::setup($settings{window_manager}, $dry_run);
print "\n";

Xorg::setup($settings{xorg_resolution}, $settings{xorg_brightness}, $dry_run);
print "\n";

Theming::setup($settings{theme}, $dry_run);
print "\n";

Browser::setup($settings{browser}, $dry_run);
print "\n";

Shell::setup($settings{shell}, $dry_run);
print "\n";

SSHAgent::setup($settings{shell}, $dry_run);
print "\n";

DefaultApps::setup($dry_run);
print "\n";

# Save config after successful run
save_config() unless $dry_run || $interactive;

print "=== bonsai setup complete ===\n";
print "Restart your session or run 'startx' to use your new environment.\n";
